[build]
  publish = "dist"
  command = "node scripts-node/optimizedBuild.js"

[functions]
  directory = "netlify/functions"

# Optimisations pour éviter de re-déployer les images
[build.environment]
  NODE_VERSION = "18"

# Cache des dépendances pour accélérer les builds
[[plugins]]
  package = "@netlify/plugin-cache-core"

# Cache persistant pour les images
[[plugins]]
  package = "@netlify/plugin-cache-optim"

# Optimisation des images
[[plugins]]
  package = "@netlify/plugin-image-optim"

# Headers pour le cache des images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/dofus-proxy?path=/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
